services:
  development:
    container_name: drones_dev
    build:
      context: .
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-1000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    group_add:
      - video
    volumes:
      - type: bind
        source: .
        target: /workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash
    network_mode: host
