services:
  development:
    container_name: drones_dev
    build:
      context: .
    runtime: nvidia  # 👈 Explicitly use the NVIDIA runtime
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-1000
      - NVIDIA_VISIBLE_DEVICES=all        # 👈 Allow access to all GPUs
      - NVIDIA_DRIVER_CAPABILITIES=all    # 👈 Enable graphics, compute, etc.
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    group_add:
      - video
    volumes:
      - type: bind
        source: /home/rambo/Projects/Drones
        target: /workspace
      - type: bind
        source: /home/rambo/.ssh/
        target: /root/.ssh/
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash
    network_mode: host
