services:
  simulation:
    container_name: quadcopter_sim
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      SIM_WORLD: ${SIM_WORLD:-warehouse}
      SIM_GUI: ${SIM_GUI:-true}
      SIM_DEMO: ${SIM_DEMO:-takeoff}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
