name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: debug
        run: ls -R

      - name: Build the Docker image
        run: docker build .--tag simulation:$(date +%s)
